In [1]:
import numpy as np

In [13]:

y=np.array([np.eye(i+1,i+2) for i in range(5)],dtype=object)
y[0]=4
y

array([4, array([[1., 0., 0.],
                 [0., 1., 0.]]), array([[1., 0., 0., 0.],
                                        [0., 1., 0., 0.],
                                        [0., 0., 1., 0.]]),
       array([[1., 0., 0., 0., 0.],
              [0., 1., 0., 0., 0.],
              [0., 0., 1., 0., 0.],
              [0., 0., 0., 1., 0.]]), array([[1., 0., 0., 0., 0., 0.],
                                             [0., 1., 0., 0., 0., 0.],
                                             [0., 0., 1., 0., 0., 0.],
                                             [0., 0., 0., 1., 0., 0.],
                                             [0., 0., 0., 0., 1., 0.]])],
      dtype=object)

In [17]:
list(range(1,5))

[1, 2, 3, 4]

In [19]:
x=np.array([[1,2],[3,4]])

In [20]:
x.T

array([[1, 3],
       [2, 4]])

In [22]:
J=np.array([[0,0,0,0,1],[0,0,1,1,0]])
print(J)

[[0, 0, 0, 0, 1], [0, 0, 1, 1, 0]]
